version: '3'
services:
 db:
  image: mysql:5.7
  ports:
   - "3306"
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: somewordpress
   MYSQL_DATABASE: wordpress
   MYSQL_USER: wordpress
   MYSQL_PASSWORD: wordpress
  networks:
   - webnet  
 wordpress:
  depends_on:
   - db
  build:
   context: wordpress
   #user: www-data
   #command: git -C /build2 clone https://github.com/halilintar8/wp2.git
   #working_dir: /var/www/html
   #volumes:
   #- /etc/letsencrypt/live/www.example.com/fullchain.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem
   #- /etc/letsencrypt/live/www.example.com/privkey.pem:/etc/ssl/private/ssl-cert-snakeoil.key
   #- ./wordpress/sage/:/var/www/html/wp-content/themes/sage

  ports:
   - "80:80"
   - "443:443"
  restart: always
  environment:
   WORDPRESS_DB_HOST: db:3306
   WORDPRESS_DB_USER: wordpress
   WORDPRESS_DB_PASSWORD: wordpress
   #args: 
   # - GITHUB_KEY=${GITHUB_KEY}
  networks:
   - webnet

networks:
  webnet:

