version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    volumes:
      - /etc/letsencrypt/live/www.example.com/fullchain.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem
      - /etc/letsencrypt/live/www.example.com/privkey.pem:/etc/ssl/private/ssl-cert-snakeoil.key
    ports:
      - 80:80
      - 443:443
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

